name:                thermqtt
version:             0.1.0.0
github:              "dustin/thermqtt"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/thermqtt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  thermqtt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - thermqtt
    - net-mqtt
    - stm
    - w1-therm-haskell
    - scientific
    - bytestring
    - text
    - optparse-applicative
    - network
    - network-uri

tests:
  thermqtt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thermqtt
